"""rename address

Revision ID: 785e0cabeb07
Revises: 2ed6abe5c8d2
Create Date: 2024-08-20 12:01:45.949612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785e0cabeb07'
down_revision = '2ed6abe5c8d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=False))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
